name = "bi-connector"

[constants]
bi-atlas-short = "BI Connector for Atlas"
bi-short = "BI Connector"
download-center = "`MongoDB Download Center <https://www.mongodb.com/download-center/bi-connector>`__"
download-center-bi = "`MongoDB Connector for BI <https://www.mongodb.com/download-center/bi-connector>`__"
download-center-tableau = "`MongoDB Connector for BI <https://www.mongodb.com/download-center/bi-connector?jmp=tbl>`__"
download-center-url = "https://www.mongodb.com/download-center/bi-connector"
odbc-driver = "`MongoDB ODBC Driver for BI Connector <https://github.com/mongodb/mongo-odbc-driver/releases/>`__"
